@baseUrl=http://127.0.0.1:5001

### /store Get all store data
GET {{baseUrl}}/store

### /store/<store_id>
GET {{baseUrl}}/store/123

### /store/<store_id>
GET {{baseUrl}}/store/91621cb9426e46dc9ce18b74714b7cf0

### /store Add a new store
POST {{baseUrl}}/store
content-type: application/json

{
    "name": "My Store 1"
}

### /store Add a new store
POST {{baseUrl}}/store
content-type: application/json

{
    "name": "My Store 2"
}



### /item Get all items data
GET {{baseUrl}}/item

### /item/<item_id> Get item by id
GET {{baseUrl}}/item/123

### /item/<item_id> Get item by id
GET {{baseUrl}}/item/5265e80d3b3d4ba0af3aebc97a4f5b02

### /item Add a new item
POST {{baseUrl}}/item
content-type: application/json

{
    "name": "Table",
    "price": 17.99,
    "store_id": "bc7d9830947144eba9d81b04c301d626"
}

### /item Add a new item
POST {{baseUrl}}/item
content-type: application/json

{
    "name": "Table",
    "price": 17.99,
    "store_id": "abc"
}

### /item Add a new item
POST {{baseUrl}}/item
content-type: application/json

{
    "name": "Chair",
    "price": 12.50
}